### ISSUE TITLE
Some blocks invisible (Fluid, Portal, model, etc) with optifine

### ISSUE THREAD

**Issue by Charzidad** [XFactHD/FramedBlocks#98] opened 2022-04-11 03:01 UTC
Minecraft version 1.16.5

Forge version 36.2.33

FramedBlocks version 2.14.4

I test without optifine, I see every block shows is fine

![2022-04-10_23 30 41](https://user-images.githubusercontent.com/103396015/162657613-dd9779d0-37de-4dd5-ba97-9b8fdc66edd5.png)
![2022-04-10_23 30 50](https://user-images.githubusercontent.com/103396015/162657621-04576041-e791-4e16-9466-47da127855b2.png)
![2022-04-10_23 33 05](https://user-images.githubusercontent.com/103396015/162657628-4a784bc3-2d15-44b8-9113-3c31d13ac0ca.png)
![2022-04-10_23 34 26](https://user-images.githubusercontent.com/103396015/162657633-3c2e8a9e-a066-4c8d-ab42-25045e41ae69.png)
![2022-04-10_23 35 57](https://user-images.githubusercontent.com/103396015/162657635-2073be97-27d8-41bc-a1ad-bb08f56f418d.png)

I really dont know, something weird chunk invisible near other chunk with framed block

**Comment by XFactHD** [comment] 2022-04-11 06:03
Duplicate of #88.

**Closed as completed** 2022-04-11 06:03 UTC
Labels: bug, duplicate, 1.16, optifine
