### ISSUE TITLE
[Feature]: Cut Corner Block

### ISSUE THREAD

**Issue by theJERMwarfare** [XFactHD/FramedBlocks#356] opened 2024-01-08 05:13 UTC
### Describe the feature

A block with a similar shape to stairs with a slope where there would normally be the steps connecting the edge of the top step and the edge of the bottom step. The block should be able to be placed horizontally or vertically (may need to be two different blocks) so that it could be used in a corner between two Framed Panels (vertical slabs) or to connect a slab (upper or lower) and a framed panel.

A quick blender rendered example:
![Framed Block_Cut Corner Block](https://github.com/XFactHD/FramedBlocks/assets/47936735/4478d980-1f7c-4066-8bc1-fd15412c413c)

A screenshot from Minecraft showing a empty corner with Framed Panels on either side where this block would fill in the empty corner, connecting the framed Panels:
![2024-01-07_23 46 32](https://github.com/XFactHD/FramedBlocks/assets/47936735/3f5136ff-d0a5-434f-a5af-ccc1473e45cb)

**Comment by theJERMwarfare** [comment] 2024-01-08 05:15
Also, thanks a lot for all of your hard work on this mod....it is a fantastic mod that makes building in Minecraft a lot of fun.

**Comment by XFactHD** [comment] 2024-01-08 21:57
Duplicate of #248.

This type of block is already planned and will be added in an upcoming version.

Your feedback is much appreciated, I'm happy you like the mod :)

**Closed as completed by XFactHD** 2024-01-08 21:57 UTC
Labels: enhancement, new shape

**Comment by theJERMwarfare** [comment] 2024-01-10 06:32
Great, thanks.....looking forward to the addition.
