### ISSUE TITLE
[Feature]: create schematic cannon

### ISSUE THREAD

**Issue by orfox32** [XFactHD/FramedBlocks#378] opened 2024-02-04 18:34 UTC
### Describe the feature

When using schematic cannon and frame blocks you need to put the blocks manually i would like that to be automatic like a copycat panel

**Comment by XFactHD** [comment] 2024-02-04 22:25
Duplicate of #251

There is unfortunately still no good way for me to implement support for the schematicannon without absurd workarounds. I definitely want to support it though once it's reasonably possible.

**Closed as completed by XFactHD** 2024-02-04 22:25 UTC
Labels: enhancement, mod support
