### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lillosminecraft** [XFactHD/FramedBlocks#159] opened 2022-08-18 17:32 UTC
### Minecraft version

1.19

### Forge version

1.19 (41.1.0)

### FramedBlocks version

 FramedBlocks-6.2.0.jar

### Describe the bug

when i open my server on aternos with this mod, it crashes just before opening, in the log I get this:
<html>
<body>

[18Aug2022 19:10:32.026] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129, nogui]
2 | [18Aug2022 19:10:32.035] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.2 by Oracle Corporation; OS Linux arch amd64 version 5.4.0-121-generic
3 | [18Aug2022 19:10:32.255] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER
4 | [18Aug2022 19:10:32.746] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/fmlcore/1.19-41.1.0/fmlcore-1.19-41.1.0.jar is missing mods.toml file
5 | [18Aug2022 19:10:32.750] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/javafmllanguage/1.19-41.1.0/javafmllanguage-1.19-41.1.0.jar is missing mods.toml file
6 | [18Aug2022 19:10:32.753] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/lowcodelanguage/1.19-41.1.0/lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file
7 | [18Aug2022 19:10:32.770] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/mclanguage/1.19-41.1.0/mclanguage-1.19-41.1.0.jar is missing mods.toml file
8 | [18Aug2022 19:10:32.927] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/caffeine-3.1.1.jar from FramedBlocks-6.2.0.jar
9

<br class="Apple-interchange-newline">
</body>
</html>[18Aug2022 19:10:32.026] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, [2](https://aternos.org/log/#L2)0220607.102129, nogui]
[18Aug2022 19:10:32.035] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e8[3](https://aternos.org/log/#L3)0 starting: java version 17.0.2 by Oracle Corporation; OS Linux arch amd64 version 5.4.0-121-generic
[18Aug2022 19:10:32.255] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER
[18Aug2022 19:10:32.7[4](https://aternos.org/log/#L4)6] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/fmlcore/1.19-41.1.0/fmlcore-1.19-41.1.0.jar is missing mods.toml file
[18Aug2022 19:10:32.7[5](https://aternos.org/log/#L5)0] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/javafmllanguage/1.19-41.1.0/javafmllanguage-1.19-41.1.0.jar is missing mods.toml file
[18Aug2022 19:10:32.753] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/lowcodelanguage/1.19-41.1.0/lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file
[18Aug2022 19:10:32.770] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/mclanguage/1.19-41.1.0/mclanguage-1.19-41.1.0.jar is missing mods.toml file
[18Aug2022 19:10:32.927] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/caffeine-3.1.1.jar from FramedBlocks-[6](https://aternos.org/log/#L6).2.0.jar

### How to reproduce the bug

after inserting this mod in the mods folder, I go to start, it goes normal but towards the end, it crushes

### Expected behavior

it should just start up

### Additional details

sorry for my bad english but i i don't speak english so... thanks for you hard work!

### Crash log

[18Aug2022 19:10:32.026] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129, nogui] [18Aug2022 19:10:32.035] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.2 by Oracle Corporation; OS Linux arch amd64 version 5.4.0-121-generic [18Aug2022 19:10:32.255] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER [18Aug2022 19:10:32.746] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/fmlcore/1.19-41.1.0/fmlcore-1.19-41.1.0.jar is missing mods.toml file [18Aug2022 19:10:32.750] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/javafmllanguage/1.19-41.1.0/javafmllanguage-1.19-41.1.0.jar is missing mods.toml file [18Aug2022 19:10:32.753] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/lowcodelanguage/1.19-41.1.0/lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file [18Aug2022 19:10:32.770] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /server/libraries/net/minecraftforge/mclanguage/1.19-41.1.0/mclanguage-1.19-41.1.0.jar is missing mods.toml file [18Aug2022 19:10:32.927] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/caffeine-3.1.1.jar from FramedBlocks-6.2.0.jar

**Comment by XFactHD** [comment] 2022-08-18 17:59
Duplicate of #146
Update Forge to at least 1.19.1-42.0.2

**Closed as completed by XFactHD** 2022-08-18 17:59 UTC
Labels: bug

**Comment by lillosminecraft** [comment] 2022-08-18 21:58
thank you very much!:)
