### ISSUE TITLE
[Bug]: World-breaking crash when water touches a framed sign

### ISSUE THREAD

**Issue by Toastr125** [XFactHD/FramedBlocks#247] opened 2023-03-23 21:41 UTC
### Minecraft version

1.19

### Forge version

43.2.7

### FramedBlocks version

6.8.0

### Describe the bug

Crashed the game immediately the first time, then caused the game to freeze on subsequent attempts to open the world.

### How to reproduce the bug

Have water flow into a framed sign.
This won't happen with lava, and it seems kind of hit-or-miss for modded fluids. I tried ethanol from immersive engineering, no crash, then resonant ender from thermal, yes crash. Didn't test any more because creating worlds only to crash the game and brick the world gets rather tiring after the first few times.

### Expected behavior

For it to just flow around the framed sign (like what happens with water and normal signs as well as with lava and framed signs).

### Crash log

https://paste.gg/p/anonymous/b7b36a48d6b64622b3ab8ac7ee42d710

**Comment by XFactHD** [comment] 2023-03-23 21:58
Duplicate of #243.
This was fixed in 6.8.1, I'd suggest updating straight to 6.8.2 though.

**Closed as not planned** 2023-03-23 21:58 UTC
Labels: bug, duplicate, 1.18, 1.19
