### ISSUE TITLE
[Bug]: Framed Collapsible Copycat Blocks have full-block hitboxes when part of Create mod trains or other contraptions. 

### ISSUE THREAD

**Issue by AlopeRubyAspendale** [XFactHD/FramedBlocks#511] opened 2024-10-04 10:46 UTC
### Minecraft version

1.20

### (Neo)Forge version

Forge 47.3.7

### FramedBlocks version

9.3.1

### Describe the bug

I have created a Create Mod contraption utilizing Framed Collapsible Copycat Blocks, but the hitboxes for the Framed Collapsible Copycat Block default to the full-size one when the contraption is assembled. This means that, any custom corners or walls made with this block end up having a full-block hitbox when part of a Create contraption. For example, when this block is used in my Create mod trains to emulate a corner version of the Steam 'n' Rails headstock, its hitbox sticks out of the side of the train. 

### How to reproduce the bug

Place any number of Framed Collapsible Copycat Blocks down as part of a Create mod train, and use the Framed Hammer to reduce the size of this block, preferably down to half its size or smaller. Use any block on it, or no block. Then, use Create superglue to glue the train together, making sure to include the Framed Collapsible Copycat Blocks. Then, assemble the train using the Create train station block. 

### Expected behavior

The expected behaviour is that the current hitbox of the Framed Collapsible Copycat Block should be preserved when the hitbox of the overall contraption train is calculated, so that the hitbox matches the smaller appearance of the Framed Collapsible Copycat Block.

### Additional details

I'm not sure if this issue can be fixed on the FramedBlocks side or the Create side.

**Comment by XFactHD** [comment] 2024-10-04 16:28
Duplicate of #427.
This is a bug in Create's shape collection and needs to be fixed on their end. See the Create issue linked in #427 for more details.

**Closed as not planned** 2024-10-04 16:28 UTC
Labels: bug, duplicate, other mod, mod interaction, 1.20
