### ISSUE TITLE
Seems to be crashing with oprifine

### ISSUE THREAD

**Issue by ShardUsers** [XFactHD/FramedBlocks#44] opened 2021-08-02 11:10 UTC
When I go to break the blocks it seems to crash the game I have optfine installed.   [crash-2021-08-02_04.06.34-client.txt](https://github.com/XFactHD/FramedBlocks/files/6916419/crash-2021-08-02_04.06.34-client.txt)

**Comment by ShardUsers** [comment] 2021-08-02 11:14
Never mind doesn't seem to have anything to do with optifine

**Comment by XFactHD** [comment] 2021-08-02 11:21
Duplicate of #42

**Closed as completed by XFactHD** 2021-08-02 11:21 UTC
Labels: bug, duplicate, 1.16, optifine
