### ISSUE TITLE
Incompatibility with Project MMO (1.16.5)

### ISSUE THREAD

**Issue by Kalastra** [XFactHD/FramedBlocks#90] opened 2022-03-25 18:53 UTC
- Minecraft version: 1.16.5
 - Forge version: 36.2.20
 - FramedBlocks (v2.14.1) 
 - [Project_MMO-1.16.5-3.67.5.jar]

Mining up any placed framed block in a game with PMMO installed crashes the game. Tested with only FramedBlocks and FramedBlocks+PMMO installed in singleplayer.

[crash-2022-03-25_19.30.37-server.txt](https://github.com/XFactHD/FramedBlocks/files/8353136/crash-2022-03-25_19.30.37-server.txt)

**Comment by Kalastra** [comment] 2022-03-25 21:19
Looks like it may be an issue from the PMMO side, based on discussion from the Project MMO Discord.

**Comment by XFactHD** [comment] 2022-03-26 02:00
Yes. I talked with one of their devs and they plan to fix this on their side. I'll keep this issue open until the crash is confirmed to be fixed.

**Comment by XFactHD** [comment] 2022-06-10 22:57
After talking with the Project MMO devs, I'll close this. The issue will be fixed at their discretion, though no guarantee on it.
Due to the release of 1.19 a few days ago, I will be dropping support for 1.16.5 shortly anyway.

**Closed as completed by XFactHD** 2022-06-10 22:57 UTC
Labels: bug, 1.16, other mod
