### ISSUE TITLE
[Bug]: FramedBlocks 6.2.0 on Forge 1.19 - 41.1.0 works on client but not server

### ISSUE THREAD

**Issue by DiamondKing9998** [XFactHD/FramedBlocks#168] opened 2022-09-04 01:08 UTC
### Minecraft version

1.19

### Forge version

41.1.0

### FramedBlocks version

6.2.0

### Describe the bug

I have about 30ish mods, and they all work fine, but FramedBlocks always crashes SPECIFICALLY on my Shockbyte server. The client loads just fine.

### How to reproduce the bug

don't rly know, i guess just install the same version of the mod on the same forge version.=

### Expected behavior

For it to work on server without crashing. here is my error log:

[04Sep2022 00:20:12.974] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129, nogui]
[04Sep2022 00:20:12.977] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.2 by Oracle Corporation; OS Linux arch amd64 version 4.19.0-21-amd64
[04Sep2022 00:20:13.129] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/minecraft/multicraft/servers/server576103/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2362!/ Service=ModLauncher Env=SERVER
[04Sep2022 00:20:13.557] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server576103/libraries/net/minecraftforge/fmlcore/1.19-41.1.0/fmlcore-1.19-41.1.0.jar is missing mods.toml file
[04Sep2022 00:20:13.559] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server576103/libraries/net/minecraftforge/javafmllanguage/1.19-41.1.0/javafmllanguage-1.19-41.1.0.jar is missing mods.toml file
[04Sep2022 00:20:13.560] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server576103/libraries/net/minecraftforge/lowcodelanguage/1.19-41.1.0/lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file
[04Sep2022 00:20:13.562] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server576103/libraries/net/minecraftforge/mclanguage/1.19-41.1.0/mclanguage-1.19-41.1.0.jar is missing mods.toml file
[04Sep2022 00:20:13.626] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Failed to load mod file META-INF/jarjar/caffeine-3.1.1.jar from FramedBlocks-6.2.0.jar

**Comment by XFactHD** [comment] 2022-09-04 01:11
Duplicate of #146
Update Forge to at least 1.19.1-42.0.2

**Closed as not planned** 2022-09-04 01:12 UTC
Labels: bug, duplicate, other mod, 1.19
