### ISSUE TITLE
[CRASH] Crash bug on server side when interacting or placing FB

### ISSUE THREAD

**Issue by SirOMGitsYOU** [XFactHD/FramedBlocks#117] opened 2022-05-28 21:27 UTC
Hi,

My players are experiencing this very on and off to replicate issue with framed blocks - 

https://paste.vcnet.work/CaTzigORbu (crash report) 

It seems to only occur when using forge hybrid so I would understand if it's not fixable on your end I can take it to them to fix.

EDIT: This is happening on latest version of Forge & FB

**Comment by XFactHD** [comment] 2022-05-28 21:59
Duplicate of #93, #96 and #103.
This is not fixable on my end. Bukkit server implementations are violating expectations from the vanilla game, making them impossible to support without extensive and possibly detrimental workarounds.

**Closed as not planned by XFactHD** 2022-05-28 21:59 UTC
Labels: duplicate, wontfix, 1.16, other mod

**Comment by SirOMGitsYOU** [comment] 2022-05-28 22:09
> Duplicate of #93, #96 and #103. This is not fixable on my end. Bukkit server implementations are violating expectations from the vanilla game, making them impossible to support without extensive and possibly detrimental workarounds.

No worries, thank you for replying. I'm really awful when it comes to finding related issues as I always seem to get shouted at for "hijacking" when it looks to be similar but thank you I've raised it with Catserver which is the hybrid in use here and hopefully they can fix it thank you for confirming
