### ISSUE TITLE
[Bug]: Framed Iron Door Interaction with Quark

### ISSUE THREAD

**Issue by Jophire** [XFactHD/FramedBlocks#213] opened 2022-11-22 06:11 UTC
### Minecraft version

1.19

### Forge version

43.1.47

### FramedBlocks version

6.6.1

### Describe the bug

Double framed iron doors will partially open when interacted with by hand.

The opposite door from the one clicked is the will revert to an opened state until a block update causes it to check for redstone input.

### How to reproduce the bug

Place two iron framed doors next to each other.
Right click the left to cause the right to open.
Right click the right to cause the left to open.

### Expected behavior

Neither door should open except for a redstone input.

### Additional details

I think it most likely is an issue with quarks door tweak that lets you open double doors at the same time. Regular iron doors do not have this issue however.

**Comment by XFactHD** [comment] 2022-11-22 11:17
I can't reproduce this with just FramedBlocks and Quark. The double door implementation in Quark is written in a way that guards well against this sort of issue.
Please provide a full mod list so I can look into this further. The easiest way is to produce a debug crash by holding F3+C for 10 seconds and putting that on https://gist.github.com.

**Comment by Jophire** [comment] 2022-11-22 19:11
Modlist: All The Mods 8 v1.0.1
Thought it might be quark since it was the only mod that showed up when I searched door in config.
[crash-2022-11-22_14.02.13-client.txt](https://github.com/XFactHD/FramedBlocks/files/10070296/crash-2022-11-22_14.02.13-client.txt)
[output2.webm](https://user-images.githubusercontent.com/36978900/203401289-ca1a9c1d-2f73-444c-aa9a-b6acf44a3164.webm)

**Comment by XFactHD** [comment] 2022-11-22 23:19
Together with the ATM devs I found out that this is caused by the implementation of double door opening in UtilitiX. The UtilitiX devs are aware of the issue and looking into it.
As such I'll close this issue for now. I'll keep you posted on any news regarding this from UtilitiX.

**Closed as completed by XFactHD** 2022-11-22 23:19 UTC
Labels: bug, mod interaction, 1.19
