### ISSUE TITLE
Weird shades on White alabaster (Environmental Tech)

### ISSUE THREAD

**Issue by Hiranus** [XFactHD/FramedBlocks#38] opened 2021-07-18 09:16 UTC
![obraz](https://user-images.githubusercontent.com/6943031/126061968-44a6aaad-5a19-4269-8836-16cee96f9684.png)

I use All The Mods 6 pack with some additional mods, but I dont use sodium, optifine etc.

**Comment by XFactHD** [comment] 2021-07-18 10:21
Please make sure the `forgeLightPipelineEnabled` and `experimentalForgeLightPipelineEnabled` settings in the forge-client.toml config file are set to true.
If the problem persists with these settings, then I need you to provide the specific versions of Forge and FramedBlocks (a forced crashreport on pastebin.com or gist.github.com would be useful as well).

**Comment by Hiranus** [comment] 2021-07-18 12:59
![obraz](https://user-images.githubusercontent.com/6943031/126067886-15075595-21da-4a59-bb1b-a990b3f089bd.png)
It.. partially worked. Now shadows on light gray parts (framed prism corner) look weird.

**Comment by XFactHD** [comment] 2021-07-18 13:03
That's a known issue that I am currently looking into but haven't found the root cause yet.

**Comment by XFactHD** [comment] 2021-07-18 13:22
Found the problem, will be fixed in the next release.

**Closed as completed** 2021-07-18 13:21 UTC
Labels: bug, 1.16
