### ISSUE TITLE
Framed Blocks Server Crash

### ISSUE THREAD

**Issue by SirOMGitsYOU** [XFactHD/FramedBlocks#102] opened 2022-04-23 14:28 UTC
Hi, Experiencing this server crash on 1.16.5

[crash-2022-04-23_14.24.40-server.txt](https://github.com/XFactHD/FramedBlocks/files/8547396/crash-2022-04-23_14.24.40-server.txt)

**Comment by XFactHD** [comment] 2022-04-24 21:19
Duplicate of #93 and #96

**Closed as completed by XFactHD** 2022-04-24 21:19 UTC
Labels: duplicate, wontfix, 1.16
