### ISSUE TITLE
[Bug]: Server crashes on startup

### ISSUE THREAD

**Issue by nevos08** [XFactHD/FramedBlocks#148] opened 2022-08-04 18:55 UTC
### Minecraft version

1.19

### Forge version

41.1.0

### FramedBlocks version

6.2.0

### Describe the bug

My dedicated server crashes instantly on startup saying the following:
[Image](https://imgur.com/a/BR0tTSQ)

### How to reproduce the bug

Just put the jar file in the mods folder and start the forge server.

### Expected behavior

The server should start normally

**Comment by XFactHD** [comment] 2022-08-04 19:05
Duplicate of #146
Update Forge to 1.19.1-42.0.2

**Closed as completed** 2022-08-04 19:06 UTC
Labels: bug, duplicate, other mod, 1.19
