### ISSUE TITLE
[Feature:] internal and external corners for the double height slopes for roofing and cap to match

### ISSUE THREAD

**Issue by xElandriax** [XFactHD/FramedBlocks#191] opened 2022-10-24 09:35 UTC
### Describe the feature

The mod is excellent but seems to be missing a selection of blocks to make a complete array (see screenshot below)

IE, internal and external corners for the double-height slopes and cap 

![2022-10-23_22 43 58](https://user-images.githubusercontent.com/66781812/197495447-df56054b-9c38-49c3-9b7b-afe60fd1760f.png)

It would be lovely if these were planned for a future release, it will make the mod's versatility much better :)

**Comment by XFactHD** [comment] 2022-10-24 10:13
Duplicate of #156
These shapes are already planned, will take some time to implement though :)

**Closed as completed** 2022-10-24 10:13 UTC
Labels: duplicate, enhancement, new shape
