### ISSUE TITLE
Shading issues with slopes.

### ISSUE THREAD

**Issue by Elpximso** [XFactHD/FramedBlocks#14] opened 2021-04-16 17:11 UTC
I am playing All the mods 6 to the sky and im having shading issues when using the framed slopes, i am using optifine and did change the config for ferritcore, that fixed the texture issues. But can this be fixed somehow or ?
![2021-04-16_19 08 50](https://user-images.githubusercontent.com/49398814/115059835-65f32680-9ee7-11eb-87f4-4f0e0b448d65.png)

**Comment by XFactHD** [comment] 2021-04-16 17:38
Which version of Forge and FramedBlocks?
This looks very similar to issue #5, please try the solution given there and report back if it works.

**Comment by Elpximso** [comment] 2021-04-16 18:12
I will give that a try :D

**Comment by Elpximso** [comment] 2021-04-16 18:23
That didnt work, but i did turn smoot lighting level off, that apparently did some shadow stuff and it fixed it :D

**Comment by XFactHD** [comment] 2021-04-16 18:24
Please also try it without OptiFine with smooth lighting enabled.

**Comment by Elpximso** [comment] 2021-04-16 18:28
The option optifine added, i disabled that, the vanilla smooth lighting is still on 

![Screenshot_1](https://user-images.githubusercontent.com/49398814/115068205-3a296e00-9ef2-11eb-90d9-3b03505d0449.png)
![Screenshot_2](https://user-images.githubusercontent.com/49398814/115068211-3d245e80-9ef2-11eb-9ebb-c7af087a296c.png)

**Comment by XFactHD** [comment] 2021-04-16 18:31
Oh, ok, then it is probably just OptiFine fucking up the Forge light pipeline.
I will close this as "OptiFine is not supported" because I can't do anything against problems caused by them.

**Closed as completed by XFactHD** 2021-04-16 18:31 UTC
Labels: bug, wontfix, 1.16, optifine

**Comment by Elpximso** [comment] 2021-04-16 18:34
Yeah think so too, thanks for the help tho :D
