### ISSUE TITLE
[Bug]: Maps aren't loading in framed item frames if only source of visibility is the framed item frame

### ISSUE THREAD

**Issue by michelle1574** [XFactHD/FramedBlocks#318] opened 2023-09-24 12:50 UTC
### Minecraft version

1.19

### Forge version

43.2.23

### FramedBlocks version

6.8.4

### Describe the bug

When maps attached to framed item frames, and exited the server and reentered, the maps that arent in your hand are just an icon.

### How to reproduce the bug

Get some maps,
Place the framed item frames, place the maps on it. Delete the maps (i mean to destroy them or put them in chest)
exit the server
and reenter

### Expected behavior

The maps would render like on normal item frames.

**Comment by XFactHD** [comment] 2023-09-24 13:09
Duplicate of #309. This is fixed in FramedBlocks 6.8.6 and 9.1.1 for 1.19.2 and 1.20.1 respectively.

**Closed as completed by XFactHD** 2023-09-24 13:09 UTC
Labels: bug, duplicate, 1.19, 1.20

**Comment by michelle1574** [comment] 2023-09-30 08:12
Sorry, I updated the mod. No fix. Please reopen the post

**Comment by michelle1574** [comment] 2023-09-30 08:30
The only fix was to pick up a single map from a framed item frame. Please make it automatic.
