### ISSUE TITLE
[Feature]: Double Framed Sloped Stairs +Double Framed Vertical Sloped Stairs

### ISSUE THREAD

**Issue by Gregie** [XFactHD/FramedBlocks#474] opened 2024-07-31 18:57 UTC
### Describe the feature

Just something I noticed and thought of a few ways to use. The "Framed Sloped Stairs" and "Framed Vertical Sloped Stairs" don't have a valid fill option like the "Framed Double Stairs" and "Framed Vertical Double Stairs". From scrolling through the other bugs/suggestions it seems like the divided stairs in the works would solve this by layering together a "Framed Slab" and a "Framed Double Half Slope". I love building with slabs and what I was trying to do just happened to need these types of blocks to pull off the seamless look. Thank you for the hard work on the mod and I can't wait to see what updates are in store!

**Comment by XFactHD** [comment] 2024-07-31 21:02
Duplicate of #368.
Both sliced versions where the slab and half slope are separate parts and double versions where the existing sloped stairs is filled to a full cube with a second half slope are already planned. A full cube version where the half slopes at the top can both have different camos compared to the slab part are not possible for technical reasons.

**Closed as completed by XFactHD** 2024-07-31 21:02 UTC
Labels: enhancement, new shape
