### ISSUE TITLE
[Bug]: Framed item frame maps don't load automatically

### ISSUE THREAD

**Issue by michelle1574** [XFactHD/FramedBlocks#327] opened 2023-09-30 08:32 UTC
### Minecraft version

1.19

### Forge version

(probably not needed)

### FramedBlocks version

6.8.6

### Describe the bug

Something related to #318 but now partially fixed. The only thing you need to do is pick up a single map from the framed item frame.
Please make it automatic.

### How to reproduce the bug

As in #318 

### Expected behavior

As in #318

**Comment by XFactHD** [comment] 2023-09-30 10:41
Making the maps load automatically was the whole point of the fix for #309 (which #318 is a duplicate of), having to hold a map in your hands was the incorrect behaviour that prompted the original issue report. Testing in my dev environment shows that the fix behaves as expected in both singleplayer and multiplayer: the maps in item frames are immediately loaded without having to hold an item in your hand.

Please make sure that your client and, if you are playing in multiplayer, also the server is definitely running FramedBlocks 6.8.6. If that is the case, then the only explanation is a mod conflict, in which case I need a full latest.log as well as a debug crash report (hold F3 + C in-game until the game crashes).

**Comment by XFactHD** [comment] 2023-10-14 23:27
I'm going to assume that making sure both server and client are updated fixed your issue. If it didn't, please provide additional information on your setup including a full mod list (preferrably through a debug crash report created by holding F3+C until the game crashes).

**Closed as completed by XFactHD** 2023-10-14 23:27 UTC
Labels: bug
