### ISSUE TITLE
[Feature]: Not sure what to call this, but basically a different way for block placement according to where you are pointing at

### ISSUE THREAD

**Issue by EmmaRavens** [XFactHD/FramedBlocks#490] opened 2024-08-23 18:33 UTC
### Describe the feature

Idk how to explains this better, however I was thinking of making it so that depending on where you pointing to, it will change the block placement.

Following the screenshot below would make it so that if you pointing to the left or right it will place the slab in the vertical, up or down would be horizontal, center would be centered blocks.
![image](https://github.com/user-attachments/assets/ec6b31f8-e0e8-4649-a35c-c973fada4322)

For the center if you pointing at the upside or downside of a block would be a vertical centered slab, if pointing at any side of a block would be a horizontal centered slab. Or instead of the previous way, it would be depending on where the player is, above or below a block will place a horizontal centered slab, if the player is on any side of the block will be a vertical centered slab

Like this
https://i.imgur.com/OnxYZfA.mp4

Got that from [Additional Placements](https://modrinth.com/mod/additional-placements) mod

**Comment by XFactHD** [comment] 2024-08-30 03:59
Duplicate of #485 
See my response here for more details: https://github.com/XFactHD/FramedBlocks/issues/485#issuecomment-2319962402

**Closed as not planned by XFactHD** 2024-08-30 03:59 UTC
Labels: enhancement, new mechanic
