### ISSUE TITLE
[Mod Support]: Create Schematicannon doesn’t work with framed blocks

### ISSUE THREAD

**Issue by Cuttleguy** [XFactHD/FramedBlocks#414] opened 2024-03-30 20:07 UTC
### The mod to integrate with

https://www.curseforge.com/minecraft/mc-mods/create

### Describe the feature

Create mod’s schematic canon doesn’t place the camouflage for framed blocks. This is because it doesn’t copy nbt data. That is because it uses the structure template class. The way I suggest to fix this is to change it so the camouflage is also included in the block state. Also there is an interface you can implement to change the schematic canon requirements. Using this interface, you could make the schematic canon require the camouflage block. I am 1.18, but this would be useful for all versions 1.16+(and maybe before).

**Comment by Cuttleguy** [comment] 2024-03-30 20:25
In 1.18. I am not 1.18

**Comment by XFactHD** [comment] 2024-03-31 01:42
Duplicate of #251

Putting the camo into the blockstate is not possible, all blockstates are computed by the game during startup and attaching data with almost infinite possible values to blockstates is prevented by their underlying design.

I am aware of the existence of the two interfaces that are needed to make this work, I even have a TODO comment referencing them so I don't forget about it. The issue is that the way they need to be implemented would require making Create a mandatory dependency of FramedBlocks, which is simply not an acceptable solution. I have made an issue on their repository to get an alternate approach implemented such that the integration with Create is optional and implementation of that seems to be moving forward. Time will tell when it's ready.

Also, as it stands currently, this would only be implemented in 1.20.1 and later, all prior versions are not supported anymore as I do not have time to maintain more than two versions (the second of which is 1.20.4, which is still unreleased as I'm doing major changes to core systems)

**Closed as completed by XFactHD** 2024-03-31 01:42 UTC
Labels: enhancement, mod support
