### ISSUE TITLE
[Feature]: stairs/ slabs with panes

### ISSUE THREAD

**Issue by hellwolf95** [XFactHD/FramedBlocks#500] opened 2024-09-14 03:08 UTC
### Describe the feature

its just stairs and slabs with a block in the center like glass panes or the iron bars.

**Comment by XFactHD** [comment] 2024-09-15 21:22
Duplicate of #296.

This is unfortunately not feasible to implement. The amount of possible blocks this would apply to is simply not manageable.

**Closed as not planned by XFactHD** 2024-09-15 21:22 UTC
Labels: duplicate, enhancement, new mechanic

**Comment by hellwolf95** [comment] 2024-09-15 21:57
dang that sucks
