### ISSUE TITLE
[Bug]: Framed Blocks with Double Doors can't be decorated.

### ISSUE THREAD

**Issue by Ayria** [XFactHD/FramedBlocks#153] opened 2022-08-08 11:33 UTC
### Minecraft version

1.18

### Forge version

40.1.68

### FramedBlocks version

5.4.0

### Describe the bug

I have Double Doors, if you use that with Framed Blocks and you place more than one trapped door, gate, regular door, etc, you can't decorate the Framed doors/gates. 

You can place one side of a door, decorate it, and place another and trying to decorate it and it just opens and closes the door.

I can post this to Double Doors github too if you think I should.

Side not, wanted to make you aware that if you use Carryon with this mod and you pick up a door using carryon (albeit accidentally) it creates a ghost item you cant drop or remove. (You have to die to get rid of it)

### How to reproduce the bug

Install Double Doors & Framed Blocks

Place two doors or gates side by side and attempt to decorate.

### Expected behavior

Expect to be able to decorate both doors or gates that are placed side by side in any direction.

### Additional details

Mod also needed to reproduce bug: [Double Doors 3.3](https://www.curseforge.com/minecraft/mc-mods/double-doors)

**Comment by XFactHD** [comment] 2022-08-08 14:48
Duplicate of #84.
Unfortunately there is nothing I can do about this. See the linked issue for the explanation and workarounds.

**Closed as completed** 2022-08-08 14:49 UTC
Labels: bug, duplicate, 1.18, other mod, 1.19

**Comment by Ayria** [comment] 2022-08-09 10:58
Oh! Thanks! I should have looked before I posted. My bad!
