### ISSUE TITLE
[Bug]: CRASH SERVER

### ISSUE THREAD

**Issue by chesco0919gamer** [XFactHD/FramedBlocks#160] opened 2022-08-19 15:29 UTC
### Minecraft version

1.16 - UNSUPPORTED

### Forge version

1.16.5

### FramedBlocks version

FramedBlocks-2.16.1.jar

### Describe the bug

Hello how are you? I hope you are well. And an apology for the inconvenience, really sorry.
I just want to know if you can help me with this error on my server, it happens when I try to occupy some item of your mod, almost all of them.
My this is the error code.
Game in Minecraft Forge 1.16.5
and occupies the newest version of the mod for that version.

What I can do?

 

### How to reproduce the bug

---- Minecraft Crash Report -------- Minecraft Crash Report ----// Shall we play a game?
Time: 8/19/22 10:40 AMDescription: Exception in server tick loop
java.lang.NullPointerException: Exception in server tick loop at xfacthd.framedblocks.common.tileentity.FramedTileEntity.checkSolidStateOnLoad(FramedTileEntity.java:528) ~[framedblocks:2.14.2] {re:classloading} at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_312] {} at xfacthd.framedblocks.common.util.EventHandler.onServerTick(EventHandler.java:84) ~[framedblocks:2.14.2] {re:classloading} at net.minecraftforge.eventbus.ASMEventHandler_816_EventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.fml.hooks.BasicEventHooks.onPreServerTick(BasicEventHooks.java:113) ~[forge:?] {re:classloading} at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1001) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:818) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312] {}

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.16.5 Minecraft Version ID: 1.16.5

### Expected behavior

It won't let me use the mod

**Comment by XFactHD** [comment] 2022-08-19 17:36
1. Duplicate of #93, #96, #103, #117 and #143.
2. 1.16 support was dropped recently
3. Forge-Bukkit hybrid servers are impossible to support because they regularly deviate from the way the base game works, which is the cause of this crash

**Closed by XFactHD** 2022-08-19 17:36 UTC
Labels: bug, wontfix, 1.16, other mod
