### ISSUE TITLE
[Bug]: game crashes when i hold out framed stacked slope block

### ISSUE THREAD

**Issue by Konasagi** [XFactHD/FramedBlocks#518] opened 2024-10-22 22:02 UTC
### Minecraft version

1.20

### (Neo)Forge version

47.2.0

### FramedBlocks version

9.2.1

### Describe the bug

whenever i have the block in my hand (after placing it once), the game crashes instantly. when it puts me back in the launcher, it gives me the message "direction must be perpendicular".
![image](https://github.com/user-attachments/assets/6c3832b1-8a3d-4e3a-b2fe-e84de2059c2f)
blocks placed before the bug happens arn't affected, but when i load a backup when i have nothing in my hands, it works just fine.

remaking the physics entity also fixes the bug, and thankfully it was just the base of the tank when this happened, but it would suck for it to happen when the tank is almost complete.

### How to reproduce the bug

when i try reproducing it in a new world, the slopes place just fine. but when i go into the affected world, it unreliably crashes me. sometimes it doesn't, sometimes it does. i recorded a video of what happens here.
https://www.youtube.com/watch?v=Fwzgpo_Jlhg

### Expected behavior

to not crash

### Crash log

[crash-2024-10-22_17.23.38-client.txt](https://github.com/user-attachments/files/17482227/crash-2024-10-22_17.23.38-client.txt)

**Comment by XFactHD** [comment] 2024-10-22 22:38
Duplicate of #425.
Update FramedBlocks to 9.2.2 or later (ideally 9.3.1 which is the latest version for 1.20.1). This is caused by Valkyrien Skies and the aforementioned version protects against this.

**Closed as completed by XFactHD** 2024-10-22 22:38 UTC
Labels: bug, mod interaction, 1.20

**Comment by Konasagi** [comment] 2024-10-22 23:08
> Duplicate of #425. Update FramedBlocks to 9.2.2 or later (ideally 9.3.1 which is the latest version for 1.20.1). This is caused by Valkyrien Skies and the aforementioned version protects against this.

thanks, i'll do that. this is the first time posting any sort of report on github so i didn't realize there were closed reports i could look at. sorry if i took up some time.

**Comment by XFactHD** [comment] 2024-10-23 00:26
No worries, thank you for taking the time to report it in the first place :)
