### ISSUE TITLE
[Feature]: X-axis divided framed stairs

### ISSUE THREAD

**Issue by 1foxy2** [XFactHD/FramedBlocks#304] opened 2023-09-03 11:21 UTC
### Describe the feature

A framed stairs but divided on X-axis so the bottom part of stairs could be diamond block and the top part could be gold block for example

**Comment by XFactHD** [comment] 2023-09-03 14:13
Duplicate of #165.
This block is planned but I'm still stuck on finding a concise and sensible name.

**Closed as completed by XFactHD** 2023-09-03 14:13 UTC
Labels: enhancement, new shape
