### ISSUE TITLE
[Bug]: Some transparent leaf blocks, when applied to a frame, display a pane of texture only when viewed from below.

### ISSUE THREAD

**Issue by IIIpl4sm4III** [XFactHD/FramedBlocks#454] opened 2024-06-28 13:12 UTC
### Minecraft version

1.19

### Forge version

43.3.7

### FramedBlocks version

6.8.6

### Describe the bug

In this example, a leaf block is applied to a large framed button. When viewed from below, the texture of the applied block can be seen as a floating pane.
![javaw_Mrzr1kaLnI](https://github.com/XFactHD/FramedBlocks/assets/5325131/66f000b7-99d4-493c-9208-54535a6a23e4)
![image](https://github.com/XFactHD/FramedBlocks/assets/5325131/aebbca96-264c-42ea-a5af-4652b8ca4806)

### How to reproduce the bug

Apply a leaf block to a large or small framed button, then view it from below.

### Expected behavior

N/A

**Comment by XFactHD** [comment] 2024-06-29 10:30
I cannot reproduce this in any supported version (1.20.1 and 1.21). Please provide a mod list of a minimum reproduction case, otherwise I cannot help you at all.

**Comment by IIIpl4sm4III** [comment] 2024-06-29 10:52
> I cannot reproduce this in any supported version (1.20.1 and 1.21). Please provide a mod list of a minimum reproduction case, otherwise I cannot help you at all.

No worries. Just to let you know the bug report section does say 1.19.2 is still supported. 
![image](https://github.com/XFactHD/FramedBlocks/assets/5325131/9fd1dd76-5b7f-4c54-92fd-ce015cf3ad04)

**Comment by XFactHD** [comment] 2024-06-29 14:48
Yeah, I always forget to update that 😅.

Regardless, if you can provide a mod list for a minimum reproduction case, then I can at least try to advise what might be causing it. The version support mainly refers to those versions not getting any updates anymore.

**Comment by XFactHD** [comment] 2024-08-04 03:07
I'm gonna close this for now. If you do provide a mod list (ideally of a minimal reproduction case) later, then I'll take another look and reopen this issue if necessary

**Closed as not planned by XFactHD** 2024-08-04 03:07 UTC
Labels: bug
