### ISSUE TITLE
[Feature]: Ability to add Lilly pad to stairs

### ISSUE THREAD

**Issue by PhoenixB1ood** [XFactHD/FramedBlocks#444] opened 2024-06-05 02:48 UTC
### Describe the feature

It would be cool if you could add the ability to add lily pads to waterlogged stairs, similar to vanilla stairs
![javaw_hEVN4qEHn4](https://github.com/XFactHD/FramedBlocks/assets/150571478/a8442c2c-43c9-4aad-9466-fc700c4b6f37)

**Comment by XFactHD** [comment] 2024-06-13 12:27
This is caused by a bug that is outside of my control. It may be possible to fix this in 1.21, but I won't be able to do anything about this in earlier versions.

**Comment by XFactHD** [comment] 2024-08-04 03:09
This is fixed in the 1.21 releases of FramedBlocks.

**Closed as completed by XFactHD** 2024-08-04 03:09 UTC
Labels: bug, 1.21
