### ISSUE TITLE
Add framed sliding doors

### ISSUE THREAD

**Issue by IlikePlaystationandXbox** [XFactHD/FramedBlocks#317] opened 2023-09-24 11:07 UTC
### Describe the feature

We **need** sliding doors like create ones, Because i really like those doors in create that slide and _probably_ everyone else does too.

**Comment by XFactHD** [comment] 2023-09-24 13:18
Duplicate of #184.
This is something I want to add at some point but I'm not entirely sure how yet as it would require a very significant amount of code duplication.

**Closed as completed by XFactHD** 2023-09-24 13:18 UTC
Labels: enhancement, new shape
