### ISSUE TITLE
Potential improvements / suggestions

### ISSUE THREAD

**Issue by HipHopHuman** [XFactHD/FramedBlocks#7] opened 2021-03-18 23:07 UTC
Loving the mod so far, out of BlockCarpentry and FramedBlocks, FramedBlocks is slowly earning my preference because it looks better, has a smaller footprint and more shape options. I still think there are two major improvements that could be made (if within scope) to solidify it's place as *the* cursed wedge shaped mod in 1.16 :P

I'm adding sloped blocks to a pretty extensive build and noticing parts of said build that would look infinitely better if FramedBlocks:

- Supported glass textures on the framed blocks. It would make situations like this more uniform:
    
  ![image](https://user-images.githubusercontent.com/70091260/111706987-f0def380-884b-11eb-8399-9fe6c9f95828.png)

- Supported two framed blocks within the same block space where it makes sense and the shapes logically fit together. For example, two horizontal slopes, each with a different texture, for smoothing diagonal connections:

  ![image](https://user-images.githubusercontent.com/70091260/111707557-f25ceb80-884c-11eb-8df8-c36fecab167c.png)

  I'm aware that mixing double slabs is a technical challenge (the Double Slabs mod does it somehow, but it tanks performance). I'm unsure if the same technical limitations would apply to the custom blocks in this mod. Even if the implementation details were really basic and it acted as a single block with a single model, just with two separate textures stitched together, that would still be acceptable as it's more the aesthetic aspect that is important, not necessarily the convenience of placing them - plus that would simplify the glowstone interaction.

- (Bonus) Supported a combination of the previous two suggestions, where a glass block can be applied as a texture to the "half-block" described in the previous suggestion.

I'm painfully unaware of how feasible or infeasible any of these suggestions are, but I have poked around a few mod code bases so I do have some understanding that this may creep into "out of scope" or "too complex" territory, so if that's the case then feel free to close this issue. Just opened it in case it is possible :)

**Comment by XFactHD** [comment] 2021-03-18 23:49
I am currently in the process of rewriting the rendering/model system. I will work on new features when that is done.

- Support for glass is something I am still looking into as I would love to have that.
- Double slabs (and double panels) should be fairly simple to add and would work the same way normal double slabs work
- Double slopes like the second picture should be equally simple but they would be a completely seperate block with an associated item for simplicity
- Mixing different shapes will not be possible as that would be a massive amount of combinations and an extremely complex model implementation

**Comment by HipHopHuman** [comment] 2021-03-22 11:56
> I am currently in the process of rewriting the rendering/model system. I will work on new features when that is done.

Understandable, absolutely no rush, I'm just happy this mod exists and I can wait as long as is necessary

> Support for glass is something I am still looking into as I would love to have that.

Awesome! Is there possibility this could extend to other transparent blocks like leaves?

> Double slabs (and double panels) should be fairly simple to add and would work the same way normal double slabs work

Are you sure? It seems like a bit of a reach to me to have it behave like double slabs (assuming you mean the double slabs mod). I'm not an expert but I've heard word of what was technically necessary to get that to work and how much of an impact it can have on performance, when just having a dedicated item for it (like the slopes) would work just as well.

> Double slopes like the second picture should be equally simple but they would be a completely seperate block with an associated item for simplicity

Awesome!

> Mixing different shapes will not be possible as that would be a massive amount of combinations and an extremely complex model implementation

Mixing two shapes is something I can definitely see as too complex, and honestly very edge-case. Most of the time you just want to have two of the *same* shape in a blockspace, but with two different textures. It would be awesome if that supported both transparent and opaque textures at the same time, but also seems like a bit of a big ask...

**Comment by XFactHD** [comment] 2021-03-22 16:05
> Awesome! Is there possibility this could extend to other transparent blocks like leaves?

I will look into the feasibility of this. The hard part is determining whether the block is solid and has only six faces without looking at the model.

> Are you sure? It seems like a bit of a reach to me to have it behave like double slabs (assuming you mean the double slabs mod). I'm not an expert but I've heard word of what was technically necessary to get that to work and how much of an impact it can have on performance, when just having a dedicated item for it (like the slopes) would work just as well.

To get a break from the tedious rewrite, I took a look and tried something out and decided to implement it immediately. The implementation is very similar to the way double slabs are built with vanilla slabs. You click a Framed Slab with the Framed Slab item to get a Framed Double Slab which then applies the camo to the upper or lower slab depending on where you click it. The model basically just asks both normal slab models for their quads with the given camo data and combines them into one list. The double panel and double slope work the same way.
![2021-03-20_02 35 49](https://user-images.githubusercontent.com/11262040/112019853-20ce1580-8b30-11eb-8016-7ecea095e0f9.png)

> Mixing two shapes is something I can definitely see as too complex, and honestly very edge-case. Most of the time you just want to have two of the _same_ shape in a blockspace, but with two different textures. It would be awesome if that supported both transparent and opaque textures at the same time, but also seems like a bit of a big ask...

Due to how the double slab, double panel and double slope are implemented, they support combining transparent/translucent and solid textures out of the box. The only thing the double blocks struggle with, is two textures with tinting support (like the grass block)

**Comment by HipHopHuman** [comment] 2021-03-23 11:10
> I will look into the feasibility of this. The hard part is determining whether the block is solid and has only six faces without looking at the model.

If it's too difficult, then it's not entirely necessary, as stuff like that could just be hidden with receding walls to achieve the same or similar look.

> To get a break from the tedious rewrite, I took a look and tried something out and decided to implement it immediately. The implementation is very similar to the way double slabs are built with vanilla slabs. You click a Framed Slab with the Framed Slab item to get a Framed Double Slab which then applies the camo to the upper or lower slab depending on where you click it. The model basically just asks both normal slab models for their quads with the given camo data and combines them into one list. The double panel and double slope work the same way.

Oh wow, that was really fast... It's looking good. This will definitely help touch up the rough edges that show up when making sloped builds.

> Due to how the double slab, double panel and double slope are implemented, they support combining transparent/translucent and solid textures out of the box. The only thing the double blocks struggle with, is two textures with tinting support (like the grass block)

That's really exciting to know, I'm not sure what blocks entail tinting support but I don't think grass blocks would be used a lot when mixing textures like this, since they already have 2 textures. Plus, one could simply use a faux grass block (assuming they don't inherit the tinting), like Quark's Turf, which has the grass texture on all 4 sides. As long as it can support glass and concrete in the same blockspace, I think that's already quite more than enough

**Comment by TenaciousLemur** [comment] 2021-03-25 12:53
While I am here might I suggest some kind of ghost block as a placement guide? I think one or two of the competition does this so that you don't end up with any unexpected placement orientations. This might be a lot of work though I am aware.

Thanks for all your hard work!

**Comment by XFactHD** [comment] 2021-03-25 14:36
I might look into adding ghost blocks at some point. No promise though.

**Comment by XFactHD** [comment] 2021-04-02 10:33
Putting glass blocks into Framed Blocks is now possible, still looking into adding other transparent/translucent blocks.
Double slabs, double panels and double slopes are done.
Ghost blocks as a placement aid is something I am still looking into.

**Comment by HipHopHuman** [comment] 2021-04-03 18:07
This is great news :) I'm not too bothered with ghost blocks as I make a lot of use of the "Rotation Lock" feature in Quark, but it does sound like a cool addition. Thanks for the amazing work!

**Comment by zymex22** [comment] 2021-04-06 06:16
will this at some point get "rounded shapes" like arches and pillars?
like ArchitectureCraft had in 1.8/1.10 or remake version from 1.12
https://www.curseforge.com/minecraft/mc-mods/architecturecraft/screenshots

i really loved that mod to easy make some awesome builds without need for using chisel and bits that took forever to do single pieces :D

anyway good job with this mod, having option to "color" standard block shapes are such a awesome addition to minecraft as it means you dont need to have 100 types of each item just "color" them instead :D

**Comment by XFactHD** [comment] 2021-04-06 16:02
Rounded shapes would theoretically be possible but the amount of quads would be really high, which could become a performance problem on large builds. Apart from that, the round parts would only be approximated instead of being really round like in ArchitectureCraft.
Besides that it wouldn't fit the theme of this mod.

**Comment by Drycinhound** [comment] 2021-04-09 21:38
I seen since the beginning. but so vertical stairs, 8x8x8pixel squares, maybe like custom stair and models(like a slab/vertical slab with a half slab/vertical half slab to make custom stairs? like block blending with possibly 
__|__
   |    (as a 4 different type blocks)

**Comment by XFactHD** [comment] 2021-04-10 12:41
I'm sorry, I am having a hard time understanding what you are suggesting. Drawing a sketch of what you are suggesting might help.

**Comment by Drycinhound** [comment] 2021-04-10 19:50
> I'm sorry, I am having a hard time understanding what you are suggesting. Drawing a sketch of what you are suggesting might help.

sure, but do you have discord as it would be easier to post images. it is hard as I am new here

**Comment by Drycinhound** [comment] 2021-04-10 19:55
![WIN_20210410_14_55_20_Pro](https://user-images.githubusercontent.com/82241481/114282962-d2b08180-9a0c-11eb-815a-644fee958cae.jpg)
so here is a rough sketch. but Block logging is like for example. putting a cobble half slab on top of a obsidian slab aka a half framed slab on top a framed slab

**Comment by Drycinhound** [comment] 2021-04-10 20:45
> Rounded shapes would theoretically be possible but the amount of quads would be really high, which could become a performance problem on large builds. Apart from that, the round parts would only be approximated instead of being really round like in ArchitectureCraft.
> Besides that it wouldn't fit the theme of this mod.

Hey I have a solution that they don’t have to be rounded yet but a pixelated

**Comment by XFactHD** [comment] 2021-04-10 21:08
> so here is a rough sketch. but Block logging is like for example. putting a cobble half slab on top of a obsidian slab aka a half framed slab on top a framed slab

Vertical stairs are something I could theoretically add, though you can already mostly achieve the desired effect with existing blocks.
Combining different shapes in one block space (ie. combining a slab with a slab edge to build stairs) is not going to happen. This goes into the realm of micro blocks which is a complexity I don't want to deal with in this mod.

> Hey I have a solution that they don’t have to be rounded yet but a pixelated

That would still be a really large amount of quads (or potentially even more than trying to approximate the round shape) and it also doesn't make it fit the theme of the mod any better.

**Comment by Drycinhound** [comment] 2021-04-10 21:13
![image](https://user-images.githubusercontent.com/82241481/114284738-abab7d00-9a17-11eb-8178-8edf130a9dff.jpg)
This caused so much lag but here is a reference for stuff to add with block logging

**Comment by XFactHD** [comment] 2021-04-10 21:24
These shapes would create an equal or similar amount of lag if they were added to FramedBlocks. Microblocks and any blocks with similar possibilities are and will always be fairly heavy on performance.

**Comment by Drycinhound** [comment] 2021-04-10 21:44
> These shapes would create an equal or similar amount of lag if they were added to FramedBlocks. Microblocks and any blocks with similar possibilities are and will always be fairly heavy on performance.

Is there a mod for micro blocks on 1.16.5? Or maybe have it as an add on mod if there isn’t?

**Comment by Drycinhound** [comment] 2021-04-10 21:44
But I mean in the image for Roof slab?

**Comment by XFactHD** [comment] 2021-04-11 00:55
> Is there a mod for micro blocks on 1.16.5? Or maybe have it as an add on mod if there isn’t?

No idea. This is also something I don't have the knowledge to implement myself.

> But I mean in the image for Roof slab?

Please elaborate what you mean.

**Comment by HipHopHuman** [comment] 2021-04-13 06:11
Can we perhaps open our own issues instead of piggybacking on mine? I'm getting a little tired of being spammed with notifications for every single person's request. I regret writing such a general title 😅

**Comment by XFactHD** [comment] 2021-04-13 07:28
You can also unsubscribe from the notifications by clicking the button on the right side of the comments or the link at the bottom of the email.

**Comment by HipHopHuman** [comment] 2021-04-15 04:44
I could, but then I lose out on being notified on the progress of my original suggestions 🤷‍♂️ .

**Comment by XFactHD** [comment] 2021-04-16 14:00
@TenaciousLemur I have implemented ghost block rendering as a placement aid.
@HipHopHuman I have extended the amount of non-solid blocks you can place in framed blocks. In a future version I will allow you to set the whitelist with a tag in a datapack.

**Comment by XFactHD** [comment] 2021-04-26 17:39
The whitelist has been moved to a tag now.
I will close this issue now as everything mentioned and confirmed as doable has been implemented.

**Closed as completed by XFactHD** 2021-04-26 17:39 UTC
Labels: enhancement, 1.16, new shape, new mechanic

**Comment by mortisimus1** [comment] 2024-08-11 16:01
I really like this mod, but is it possible to add a Framed half slope slab for the 1.20.1 version of the mod?

**Comment by XFactHD** [comment] 2024-08-13 12:56
Half slope slabs are planned, see #288. Next time please make your own issue instead of commenting on an over three years old closed issue.
