### ISSUE TITLE
[Feature]: Multiple corner cube in a single block.

### ISSUE THREAD

**Issue by Xiarno** [XFactHD/FramedBlocks#203] opened 2022-11-08 18:58 UTC
### Describe the feature

I remember in the older version, with the Microblocks mod (or whatever it was named at the time) that allowed for a lot of customizability, notably in the fact that multiples microblocks could be put together in the space of a single block. That would allow for a huge customization, notably in the form of being able to have multiples block type put in a single block arrangement.

With framed block, I think the "easiest" (to my very small knowledge & assuming capabilities) way to achieve something relatively comparable to begin with would be to allow the corner cube (Or "Framed Slab Corner") to be placed in the same block space as another one and being able to decide which block to use for each framed corner. 

This would probably be done in a similar way to this issue: https://github.com/XFactHD/FramedBlocks/issues/181#issuecomment-1287982486

**Comment by XFactHD** [comment] 2022-11-08 19:41
Duplicate of #166 
Having more than two materials in one block is not feasible for technical reasons. See https://github.com/XFactHD/FramedBlocks/issues/166#issuecomment-1236112742 for more details

**Closed as not planned by XFactHD** 2022-11-08 19:41 UTC
Labels: duplicate, enhancement, new shape

**Comment by Xiarno** [comment] 2022-11-08 19:48
Can I ask how did the microblocks mod did it at the time then?

**Comment by XFactHD** [comment] 2022-11-08 19:52
Those microblocks (including Chisels & Bits) work substantially different in certain areas.
The technical reasoning lies in the way FramedBlocks works internally.
