### ISSUE TITLE
[Feature]: Show block when in entity form

### ISSUE THREAD

**Issue by TheFireOcean** [XFactHD/FramedBlocks#144] opened 2022-07-31 06:39 UTC
### Describe the feature

Create mod turns blocks into entities when moving them and the framed blocks do not show the applied texture when moving
![2022-07-31_02 38 35](https://user-images.githubusercontent.com/67860543/182013518-6f49a00a-3ef2-43d8-b60e-7819f06d1371.png)
![2022-07-31_02 38 28](https://user-images.githubusercontent.com/67860543/182013520-11b6205c-ce03-4d3e-8d0e-08a641875683.png)
.

**Comment by XFactHD** [comment] 2022-07-31 12:48
Duplicate of #122
This is fixed in FramedBlocks 5.5.0 in combination with Create 0.5.0a

**Closed as completed** 2022-07-31 12:48 UTC
Labels: duplicate, enhancement, mod support
