### ISSUE TITLE
Rendering issues when added to Direwolf20 1.16.

### ISSUE THREAD

**Issue by TenaciousLemur** [XFactHD/FramedBlocks#8] opened 2021-03-25 12:45 UTC
Hi, I love that this exists for 1.16 as for whatever reason the other similar mods are taking a while to update. 

The mod doesn't cause any crashes or anything which is great however there are some really strange rendering bugs on both the in-world block models and the inventory ones (you can't tell them apart and they are too dark to see against the hotbar).

I have attached an example of a couple of blocks which would normally compliment each other - the inner corner prism slope and the inverse (just the corner sliced off). Some of the textures on the sides are either missing or incorrectly rotated. I have used contrasting colours in order to highlight the issue.

I am not sure if this is a mod conflict or just an in-mod bug.

Thanks for your time!

![2021-03-25_12 23 32](https://user-images.githubusercontent.com/81366227/112474676-d59e4780-8d67-11eb-95f3-9d821f69f721.png)
![2021-03-25_12 23 40](https://user-images.githubusercontent.com/81366227/112474685-d800a180-8d67-11eb-999d-1e6eac5451ee.png)
![2021-03-25_12 23 46](https://user-images.githubusercontent.com/81366227/112474690-d931ce80-8d67-11eb-86e4-dbb322e5d2b5.png)
![2021-03-25_12 23 51](https://user-images.githubusercontent.com/81366227/112474701-db942880-8d67-11eb-982d-d6a41017c6b9.png)
![2021-03-25_12 23 57](https://user-images.githubusercontent.com/81366227/112474709-dd5dec00-8d67-11eb-8b06-8de47c45310b.png)
![2021-03-25_12 24 35](https://user-images.githubusercontent.com/81366227/112474712-de8f1900-8d67-11eb-8312-f1548570acfa.png)

**Comment by XFactHD** [comment] 2021-03-25 14:35
If you have Optifine installed, please try removing it.
If you have FerriteCore installed, please disable the `bakedQuadDeduplication` option in the ferritecore-mixin.toml config file.
If this does not help, please provide a debug crash report (F3+C for 10 seconds) via gist.github.com

**Comment by TenaciousLemur** [comment] 2021-03-25 14:49
I'll give that a go thanks!

Why does optifine mess with it something to do with the texture rotation to make the ground look less uniform? I would have thought most people would have that installed in a modding context.

Thanks for the quick response!

**Comment by XFactHD** [comment] 2021-03-25 14:54
The problem with Optifine is that we can't know what they mess with since it is closed source and impossible to debug in a development environment.

**Comment by TenaciousLemur** [comment] 2021-03-25 14:55
I guess it's so far gone now that nobody is going to be able to make an open source competitor. I'll get back to you with the results of my testing in case you decide to add a lil' tip to your FAQ or something.

**Comment by XFactHD** [comment] 2021-03-25 16:52
I have added a note about the problem with FerriteCore to the mod description on CurseForge.
Please provide anything you find in your testing, so I can try to fix it or atleast warn people about it.

**Comment by TenaciousLemur** [comment] 2021-03-25 19:01
The FerriteCore thing worked. Note: The game crashed on world load once but a reload worked. Just to encourage people to be persistent with trying the solution if it crashes initially. The blocks all look good now.

**Comment by XFactHD** [comment] 2021-03-25 19:35
Please post the crash report on gist.github.com and send the link here, I would like to know if it is related to FramedBlocks or just a coincidence.

**Comment by TenaciousLemur** [comment] 2021-03-26 09:26
I'll try to dig it out but it might be lost. if it happens again I will upload it.

**Comment by khaaris** [comment] 2021-03-26 16:11
Hello, i can confirm the same bug, and its optifine, i removed shaders , mod's everything , from my side , its the optifine

**Comment by khaaris** [comment] 2021-03-26 18:02
![2021-03-26_18 01 30](https://user-images.githubusercontent.com/81433033/112674072-63a82a00-8e5d-11eb-9770-53b6273a51be.png)
and i also get this error , when i use framedblocks with optifine

**Comment by XFactHD** [comment] 2021-03-26 18:25
There is absolutely nothing I can do about that. See my comments above about OptiFine.

**Comment by khaaris** [comment] 2021-03-26 18:51
@XFactHD , yes bro i know, i just confirmed the error :D , not asking you for anything. have a good day

**Comment by TenaciousLemur** [comment] 2021-03-26 19:42
It works fine with optifine for me. I wonder how other mod authors get around the closed source issue. Trial and error?

**Comment by khaaris** [comment] 2021-03-26 19:57
or maybe its my gpu i have amd rx580

**Comment by XFactHD** [comment] 2021-03-26 20:45
> It works fine with optifine for me. I wonder how other mod authors get around the closed source issue. Trial and error?

Trial and error or pure luck that they aren't using anything that is modified in a problematic way by OptiFine.

**Comment by XFactHD** [comment] 2021-03-26 20:46
> or maybe its my gpu i have amd rx580

That is very unlikely

**Comment by XFactHD** [comment] 2021-03-31 15:50
I'm closing this as the original issue is resolved.
@TenaciousLemur If you do find that crashreport or get the crash again, feel free to post it here nonetheless.

**Closed as completed by XFactHD** 2021-03-31 15:50 UTC
Labels: bug, 1.16, other mod
