### ISSUE TITLE
 Would you port to fabric for 50 €?

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#110] opened 2022-05-09 17:26 UTC
(:

**Comment by XFactHD** [comment] 2022-05-09 18:11
Nope.
First of all, that would cost you a lot more due to the complexity of this mod and the reliance on certain parts of the Forge API, which I would need to re-write from scratch.
Secondly, I personally don't have any interest in Fabric, especially in the light of the current controversies. I prefer spending my time making things I actually use myself.

Duplicate of xfacthd/FramedBlocks#10

**Closed as completed by XFactHD** 2022-05-09 18:11 UTC
Labels: question, wontfix, fabric
