### ISSUE TITLE
Framed Rail Slopes crashes the game (& server) with Quark installed

### ISSUE THREAD

**Issue by LeumiiPix** [XFactHD/FramedBlocks#103] opened 2022-04-24 00:39 UTC
• Minecraft Version: 1.18.2
• Forge Version: v40.1.0
• FramedBlocks Version: v5.1.0
• Quark Version: v3.2-349
• AutoRegLib Version: v1.7-53

![javaw_eu1uHOvFiB](https://user-images.githubusercontent.com/104282880/164950632-1e34cbcb-bd34-4430-bde9-f3bc8e189aed.png)

Pushing a Framed Rail Slope in front of another Framed Rail Slope with Quark installed via a piston will crash the game.
This will also crash servers.

Crash logs for both client and server:
[crash-2022-04-23_20.26.43-client.txt](https://github.com/XFactHD/FramedBlocks/files/8548824/crash-2022-04-23_20.26.43-client.txt)
[crash-2022-04-23_20.28.58-server.txt](https://github.com/XFactHD/FramedBlocks/files/8548825/crash-2022-04-23_20.28.58-server.txt)

**Comment by LeumiiPix** [comment] 2022-04-24 00:53
Expected result: The block will just pop off and become an entity when pushed.
Actual result: A hard crash of whatever server this happened on, including single player.

I theorize this only happens because Quark changes how pistons work by default. This does not happen when FramedBlocks is ran by itself, as the block can't be pushed.

**Comment by XFactHD** [comment] 2022-04-24 21:03
Yeah, this is caused indirectly by Quark allowing you to move the block into a position you wouldn't be able to normally.

The crash is caused by the game trying to set the rail shape property to a shape that is disallowed, it's trying to lay the rail flat. When you place the block by hand, this is prevented by only allowing you to place the rail slope against a solid block (like the grass blocks in your screenshot).

I am going to add a temporary fix for this until a Forge PR is merged which fixes this properly.

**Closed as completed** 2022-04-24 22:36 UTC
Labels: bug, 1.16, 1.18, mod interaction
