### ISSUE TITLE
[Bug]: Quartzite blocks from Gregtech allow Xray when placed on framed blocks

### ISSUE THREAD

**Issue by Tekkitmaster27** [XFactHD/FramedBlocks#336] opened 2023-10-29 20:24 UTC
### Minecraft version

1.2

### Forge version

47.1.3

### FramedBlocks version

9.1.6

### Describe the bug

Quartzite from Gregtech version 1.0.13.b placed in any frame allows xray through the world. Allowing you to see caves and structures.      
![2023-10-29_16 06 38](https://github.com/XFactHD/FramedBlocks/assets/73328190/e0331ac5-6950-4cf1-9352-04fcedc34329)
![2023-10-29_16 06 41](https://github.com/XFactHD/FramedBlocks/assets/73328190/d756953f-ff75-414e-a520-c3732af4919b)
![2023-10-29_16 06 45](https://github.com/XFactHD/FramedBlocks/assets/73328190/9baecc46-68e2-42a7-8c16-42c41339daf3)

### How to reproduce the bug

Place Quartzite from Gregtech 1.0.13.b in any frame, can be anything from a single block to a whole wall allowing you to see though the world.

### Expected behavior

Quartzite being visible and the ability to make any frame work with it.

**Comment by XFactHD** [comment] 2023-10-29 23:35
My best guess is that this is caused by an issue with the way GregTech's block models work but unfortunately I have no way to properly test this. I am in contact with the GT devs to see who is at fault and what can be done to fix this.

**Comment by XFactHD** [comment] 2023-11-19 22:31
A recent update to GregTechCEu significantly overhauled to way their block models work and the Quartzite block and other material blocks now work properly with FramedBlocks. There are still be some blocks that excibit this issue, but the GT devs are aware of this and working on getting this fully fixed. As such I will close this as fixed from my side.

**Closed as completed by XFactHD** 2023-11-19 22:31 UTC
Labels: bug, mod interaction, 1.20
