### ISSUE TITLE
[Bug]: CRITICAL ERROR with Aternos's Server

### ISSUE THREAD

**Issue by WildLONLON** [XFactHD/FramedBlocks#147] opened 2022-08-03 20:47 UTC
### Minecraft version

1.19

### Forge version

1.19 (41.1.0)

### FramedBlocks version

6.2.0

### Describe the bug

The Aternos's Server (free French Server Host - https://aternos.org/:fr/) can't be started because of an critical error with this MOD
Don't know much about coding but i can copy/paste the Bug Report : https://mclo.gs/rm2ahoR

<img width="548" alt="Capture" src="https://user-images.githubusercontent.com/110568408/182707929-7d8b6f7e-bdb4-44aa-ae01-6d6cc1d46583.PNG">

### How to reproduce the bug

It happends when i try to start the Aternos's Server

### Expected behavior

Expected the Server to Start without any problem

### Crash log

https://gist.github.com/WildLONLON/77f18cf463ad75a49ce0dc1e3c1a9ac1

**Comment by XFactHD** [comment] 2022-08-03 20:50
Duplicate of #146

**Closed as completed by XFactHD** 2022-08-03 20:50 UTC
Labels: bug, duplicate, other mod, 1.19
