### ISSUE TITLE
Invisible Prism Corner

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#1] opened 2021-01-31 23:19 UTC
`Minecraft v1.16.5`
`Forge v36.0.7`
`Framed Blocks v2.0`

The Prism Corner is invisible when placed facing north or south.

Another couple of minor bugs is that grass blocks are not tinted when placed in a framed block, and the Framed Panel and Corner Pillar deletes the water source when first placed.

![2021-01-31_17 15 29](https://user-images.githubusercontent.com/12000593/106401198-6f8ce800-63e8-11eb-9577-69c33bda02c3.png)

**Comment by XFactHD** [comment] 2021-02-01 21:44
I cannot reproduce this on my end. Please provide a debug crash report (Hold F3+C for 10 seconds ingame) on gist.github.com, so I can take a look for possible mod conflicts.
Do you have Optifine installed?

Certain blocks deleting the water source is fixed in-dev, thanks for the info.
Grass blocks not tinting is a known issue, I have not found a satisfying solution yet.

**Comment by WenXin20** [comment] 2021-02-01 22:09
Yes, Optifine is installed, although that's the only block doing that. I'll get the crash log

**Comment by XFactHD** [comment] 2021-02-01 22:14
Please try without Optifine. I have no idea how their changes influence this mod and I have no way of fixing any problems caused by them.

**Comment by WenXin20** [comment] 2021-02-01 22:30
Yep, It's caused by optifine. Strange how that is the only slope block affected.

**Comment by XFactHD** [comment] 2021-02-01 22:34
Can you check if the Inner Prism Corner is also affected, please?

**Comment by WenXin20** [comment] 2021-02-01 22:44
That one is working perfectly.

**Comment by XFactHD** [comment] 2021-02-01 22:48
That's strange. I'll close this for now as wont-fix because I have no way of fixing stuff that breaks due to Optifine because they are closed source. Maybe I will look into this again in the future.

**Closed as completed by XFactHD** 2021-02-01 22:48 UTC
Labels: bug, wontfix, 1.16, optifine

**Comment by WenXin20** [comment] 2021-02-01 22:49
Alright, no problem.
