### ISSUE TITLE
[Feature]:  Framed Stair and Framed Vertical Stairs Divided Along Steps

### ISSUE THREAD

**Issue by theJERMwarfare** [XFactHD/FramedBlocks#359] opened 2024-01-08 08:30 UTC
### Describe the feature

It would be nice to have both the Framed Stairs and Framed Vertical Stairs divided along the step seam or make it possible to place the Framed Slab and the Framed Slab Edge within the same block space like can be done with two Framed Slabs ( same for the Framed Panel and the Famed Corner Pillar), or both options to allow a wider variety of building options such as lighting one and not the other within the same block space.

A quick Blender render example:
![Framed Block_Step Divided Stairs](https://github.com/XFactHD/FramedBlocks/assets/47936735/fb5b2885-4979-4731-8213-6713eacf46df)

**Comment by XFactHD** [comment] 2024-01-08 21:37
Duplicate of #165.

This type of block is already planned and will be added in an upcoming version.
Separate lighting state per part won't be possible though as Minecraft only allows a single light level per block.

**Closed as completed by XFactHD** 2024-01-08 21:37 UTC
Labels: enhancement, new shape

**Comment by theJERMwarfare** [comment] 2024-01-10 06:35
Thanks for the update and the explanation. Looking forward to the additional block.
