### ISSUE TITLE
[Bug]: The world is unplayable after I put water on framed trapdor.

### ISSUE THREAD

**Issue by fairdev2003** [XFactHD/FramedBlocks#461] opened 2024-07-08 17:06 UTC
### Minecraft version

1.21

### (Neo)Forge version

21.0.64

### FramedBlocks version

10.1.0

### Describe the bug

I put water on the trapdoor and it threw an "Object.hashCode()" error in the launcher, below is the crashlog in which embedium also appears, but after removing embedium and leaving the framed block mod in the "mods" folder, the problem still occurs, so I assume it is mod-side problem

### How to reproduce the bug

Its code problem. I guess framed blocks doesnt like embedium at all.

### Expected behavior

No crashes cuz its serious problem to lost world :)

### Crash log

https://gist.github.com/fairdev2003/1c7a03ad3d3c30c1da2614808af46cec

**Comment by XFactHD** [comment] 2024-07-09 22:47
Which version of ATM10 are you using? I cannot reproduce this crash in ATM10 0.9

**Comment by fairdev2003** [comment] 2024-07-10 17:34
0.9 (newest)

**Comment by fairdev2003** [comment] 2024-07-10 17:50
I placed water on framed trapdoor which was closed, How state of block is saved? In Object?. Maybe embedium is causing it in some way? I can tell you this is dangerous bug because you can lost your work and world. You can always delete mod but your work will gone

**Comment by XFactHD** [comment] 2024-07-11 02:30
Can you provide a ZIP of the affected world? This error should be impossible and at the moment I cannot reproduce it at all in ATM10 0.9.

**Comment by XFactHD** [comment] 2024-07-28 23:15
I have found the most likely cause of this crash and a fix is provided in FramedBlocks 10.1.1 which was approved earlier today on CurseForge. ATM10 will likely take a few days to update to it. As such I'm going to close this issue as fixed for now. If you can still reproduce the issue after the update, please let me know and I will re-open the issue if necessary.

**Closed as completed by XFactHD** 2024-07-28 23:15 UTC
Labels: bug, 1.21
