### ISSUE TITLE
[Bug]: Top camo of framed vertical stairs become invisible if a corner pillar is placed on top and camo'd

### ISSUE THREAD

**Issue by Xiarno** [XFactHD/FramedBlocks#204] opened 2022-11-08 19:59 UTC
### Minecraft version

1.18

### Forge version

40.1.84

### FramedBlocks version

5.8.0

### Describe the bug

The top camo of the framed vertical stairs becomes invisible/transparent if a corner pillar with camo is placed on top of it.

### How to reproduce the bug

https://user-images.githubusercontent.com/24660485/200662815-f2433778-b389-4ca7-9fec-2b12294f1152.mp4

### Expected behavior

The top part of the stairs stays opaque.

### Additional details

Playing Stone Block 3

**Comment by Xiarno** [comment] 2022-11-08 20:02
This also occurs with a corner block.
![image](https://user-images.githubusercontent.com/24660485/200663542-6067c9e4-b3f7-4d54-b67b-39e42ad2eb54.png)

**Comment by Xiarno** [comment] 2022-11-08 20:07
Also occurs while upside down too.
![image](https://user-images.githubusercontent.com/24660485/200664480-8dca593e-e99f-4baf-8f40-0f06f6de1f21.png)

**Comment by XFactHD** [comment] 2022-11-08 20:08
Duplicate of #202
This is fixed in v5.9.1

**Closed as completed by XFactHD** 2022-11-08 20:08 UTC
Labels: bug, duplicate, 1.18, 1.19
