### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Pot4to32** [XFactHD/FramedBlocks#360] opened 2024-01-08 10:49 UTC
### Minecraft version

1.20

### Forge version

47.2.0

### FramedBlocks version

9.1.6

### Describe the bug

Framed blocks with lighting will stop glowing after you reconnecting to the server. I'm running Oculus, Rubidium, Starlight, and Oculus Flywheel Compatibility patch. 

### How to reproduce the bug

Disconnect and reconnect to the server.

### Expected behavior

Glowing block will stop glowing until you update them manually by placing another block next to it.

**Comment by XFactHD** [comment] 2024-01-08 20:46
Duplicate of #294.
There is currently no way to fix this, so you'll have to remove Starlight. It's worth noting that, according to the dev himself, Starlight provides little to no benefit in 1.20 due to the changes to the light engine in vanilla itself.

**Closed as not planned by XFactHD** 2024-01-08 20:46 UTC
Labels: bug, duplicate, wontfix, 1.20

**Comment by Pot4to32** [comment] 2024-01-09 01:01
Thank you for letting me know, I had no clue what was messing with the lighting.
