### ISSUE TITLE
Some Framed blocks aren't rendering due to Optifine

### ISSUE THREAD

**Issue by tylerwoods22** [XFactHD/FramedBlocks#88] opened 2022-03-08 01:54 UTC
I know optifine is the issue causing this. This issue is present with shaders on and off. I have tried using a different version of optifine but nothing changed. Really want to use optfine. Any ideas on how to solve this
![2022-03-07_19 51 56](https://user-images.githubusercontent.com/74986954/157150420-a857133a-a177-4987-a95e-6e1004c3502d.png)
?

**Comment by XFactHD** [comment] 2022-03-08 11:07
I need a lot more info to even have a chance at finding the cause.

- Which Minecraft version?
- Which Forge version?
- Which FramedBlocks version?
- Have you tested without OptiFine?
- What happens when you put a non-solid block (i.e. glass) in the Framed Block on the left of the targeted Panel?

**Comment by tylerwoods22** [comment] 2022-03-08 14:48
- Minecraft version: 1.16.5

- Forge version: 36.2.29

- FramedBlocks version: 2.14.0 

- I have tested without optifine. Optifine is the culprit but I would like to resolve this issue while keeping optifine if possible. This issue just came up and hasn't been an issue the entirety I have played with these mods.
- The issue seems to occur when two frame blocks are touching regardless of what type of block is placed in the frame
![2022-03-08_08 44 36](https://user-images.githubusercontent.com/74986954/157261875-b45e9219-1050-4ad0-9293-84a6232e98e1.png)
![2022-03-08_08 44 54](https://user-images.githubusercontent.com/74986954/157261884-7f8dab05-0926-4a36-af6b-833d28e42c66.png)
![2022-03-08_08 47 40](https://user-images.githubusercontent.com/74986954/157261890-c4389e58-abd0-4869-a68b-cb612b6c3fe3.png)
![2022-03-08_08 47 57](https://user-images.githubusercontent.com/74986954/157261908-6c745fb1-7014-4c17-8d76-01be7b4c88d6.png)

**Comment by XFactHD** [comment] 2022-03-08 15:49
I have a suspicion why this happens. To confirm it, please try the following: backup your world, go back one FramedBlocks version and test these cases you showed again.

**Comment by tylerwoods22** [comment] 2022-03-08 16:08
Yes this solved the issue.

**Comment by XFactHD** [comment] 2022-03-08 16:45
Then my thought was correct.
I will leave this issue open for now as this is a fairly critical bug. I will have to talk to the OF devs to find a solution for this that doesn't entail yeeting yet another feature when OF is installed.

**Comment by tylerwoods22** [comment] 2022-03-08 17:22
Thank you. I was very stumped as to why this was happening

**Comment by XFactHD** [comment] 2022-03-15 19:54
I have reported this to OptiFine as this is something they have to fix.

**Comment by XFactHD** [comment] 2022-06-10 22:32
At this point I doubt the OptiFine devs will do anything about this, especially considering the recent release of 1.19. As such I will close this issue now. If you want to keep track of any eventual progress on this, keep an eye on the issue on the OptiFine repository.

**Closed as completed by XFactHD** 2022-06-10 22:32 UTC
Labels: bug, 1.16, optifine

**Comment by Casp4r** [comment] 2023-03-12 00:08
Is there any workaround available at the moment?
It worked for me with Optifine.
Now i switched from an Nvidia GPU to AMD
And my Whole map is invisible together with optifine.
I have some big buildings with Framed Blocks so i would not like to uninstall FramedBlocks 
I there not any possible Workaround?

**Comment by XFactHD** [comment] 2023-03-12 01:33
From your description, I doubt what you are seeing matches this issue. But to answer your question: There is no known workaround. OptiFine is a closed-source mod and as such it is impossible to judge how and why it may be breaking things unless there is either a crash with a very obvious error or a way to single out a specific change like was the case with this specific issue.

The only definite solution I can give you is to throw out OptiFine.
If you are using it for the performance, use Rubidium instead.
If you are using it for shaders, use Rubidium and Oculus instead.

**Comment by Casp4r** [comment] 2023-03-12 15:26
Hm okay, thanks for helping.
I tried to install Rubidium but it's crashing on startup with Error Code 1
Idk why

**Comment by XFactHD** [comment] 2023-03-12 22:00
If you provide a log from the crash via https://gist.github.com then I may be able to help you. Otherwise you are on your own.
