### ISSUE TITLE
[Feature]: slab and stair pane

### ISSUE THREAD

**Issue by WorldsOfRosefire** [XFactHD/FramedBlocks#523] opened 2024-11-02 10:29 UTC
### Describe the feature

did you got ever tired of your panes not fitting into a custom shape?
paned slab/vertical slab and paned slab is an solution:
![slab_pane](https://github.com/user-attachments/assets/451989ce-be48-4a9d-996e-921dbd32a9e4)
![stair_pane](https://github.com/user-attachments/assets/baa7368d-4aca-47e8-8d11-4c4a891633fa)

**Comment by XFactHD** [comment] 2024-11-03 20:34
Duplicate of #296 and #500.
This is unfortunately not feasible to implement. The amount of possible blocks this would apply to is simply not manageable.

**Closed as not planned by XFactHD** 2024-11-03 20:34 UTC
Labels: enhancement, new mechanic
