### ISSUE TITLE
Framed blocks not tinted correctly

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#34] opened 2021-07-05 21:40 UTC
`Minecraft v1.16.5`
`Forge v36.1.32`
`Framed Blocks v2.9.0`
[`Sodium Reforged v2.9.1`](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged)

Framed blocks are not tinted correctly when sodium is installed, not sure with which mod this needs to be fixed at. 
![2021-07-05_16 37 36](https://user-images.githubusercontent.com/12000593/124519659-92fcfa00-ddaf-11eb-8c8a-44900fbfaee2.png)

**Comment by XFactHD** [comment] 2021-07-05 22:23
This is most likely caused by changes made by Sodium. I currently do not have the time to debug this in dev. I might try to load Sodium in my dev environment when I am done with my exams.
Maybe @spoorn has an idea what might be the cause for this.

**Comment by WenXin20** [comment] 2021-07-05 22:24
Alright, no problem.

**Comment by XFactHD** [comment] 2021-07-21 23:29
I looked into it, this is caused by the biome blending feature in Sodium Reforged. A temporary fix would be to set Biome Blend to 0 in the video settings under quality.
I currently don't see how this could be fixed in either mod but maybe @spoorn has an idea.

**Comment by WenXin20** [comment] 2021-07-22 00:06
Ah, thanks! I'll give that a try.

**Comment by XFactHD** [comment] 2021-08-24 22:34
I assume the proposed solution worked.
Due to no feedback from the Sodium Reforged dev, I will close this issue as wontfix.

**Closed as completed by XFactHD** 2021-08-24 22:34 UTC
Labels: bug, wontfix, 1.16, other mod

**Comment by WenXin20** [comment] 2021-08-24 23:18
Yeah, it works, but then biome borders look really bad. But it's most likely on sodium's side.

**Comment by XFactHD** [comment] 2021-08-25 18:57
I would love to fix this because I think that this is a really cool feature but I would need atleast a hint from the Sodium dev where to even start looking for a fix.
