### ISSUE TITLE
[Mod Support]: Create Schematics

### ISSUE THREAD

**Issue by michelle1574** [XFactHD/FramedBlocks#315] opened 2023-09-23 09:32 UTC
### The mod to integrate with

Create

### Describe the feature

It would save the block that is framed if in the schematic there was framed blocks.

**Comment by XFactHD** [comment] 2023-09-23 15:53
Duplicate of #251. Keep track of that issue for any further progress on the matter.

The data is stored in the schematics but neither the creative-mode schematic placement nor the Schematicannon copy that data to the newly placed blocks by default. Create has APIs to make that possible but their current design makes it impossible for me to implement these without making Create a mandatory dependency, which is not an acceptable solution.

**Closed as completed by XFactHD** 2023-09-23 15:53 UTC
Labels: duplicate, enhancement, mod support, 1.19, 1.20

**Comment by michelle1574** [comment] 2023-09-24 12:51
What if to create an addon that will need Create and this mod?

**Comment by XFactHD** [comment] 2023-09-24 13:15
An addon can't provide this compatibility in a clean way either. The only technically possible (and absolutely awful) way to implement this in an addon could also be done in the main mod without making Create a mandatory dependency. I have used that solution once to provide compatibility with CTM, absolutely hated it because it's hell to maintain and will never use it again unless absolutely required to fix severe issues such as a crash (which this is not).
