### ISSUE TITLE
[Mod Support]: Shaders to allow framedblocks:(block) in blocks.properties file?

### ISSUE THREAD

**Issue by 34486** [XFactHD/FramedBlocks#367] opened 2024-01-19 23:49 UTC
### The mod to integrate with

Shaders (Ocolus I guess?)

### Describe the feature

So I have been able to have reflections on other modded blocks, but I would like to find a way to have reflections with framed blocks with a block inside of them.. I have added framedblocks:framed_stairs or whatever and I can have a reflective block in it but it has no reflections, I assume I should come here to ask support for this?? 

Maybe this should be question thing maybe I am putting wrong thing, there is another tag or anything? (Same thing happens to ae2 cable facade just fyi).

**Comment by XFactHD** [comment] 2024-01-22 00:01
Duplicate of #358

Making this kinda stuff work with shaders is really hard, in part because the approaches used by them for block detection are ancient and do not in any way accomodate the kind of stuff FramedBlocks' blocks and AE2's facades do. I'm keeping the linked issue open until I either know that this will definitely not be possible or until I have a way to fix it.

**Closed as completed by XFactHD** 2024-01-22 00:01 UTC
Labels: enhancement, mod support

**Comment by 34486** [comment] 2024-01-27 03:30
I do know that in 1.7 with carpenters blocks it was possible to make their blocks reflective too, I will have to look into it as i do not have it operational as of now though, I will try to figure how it worked on 1.7 on the shader side of things, but for carpenters blocks, I have no idea.

**Comment by 34486** [comment] 2024-01-27 03:50
block.10384=ArchitectureCraft:shape CarpentersBlocks:blockCarpentersSlope chisel:woolen_clay chisel:hempcrete 

Example from shaders being used with carpenters blocks mod in 1.7.10, reflections do apply. I will try to play around with framed blocks on 1.19, same exact complementry shaders version 4.7.2. 

Do you have a 'base block' like "ArchitectureCraft:shape"??? Maybe this provides some info for you, not sure.

**Comment by XFactHD** [comment] 2024-02-01 13:24
In theory this would still be possible, but you'd have to add all 180 blocks to the list and in practice it also doesn't actually achieve anything useful, adding the framed blocks to one of those ID entries will just add the effect of that entry to any block you put into a framed block instead of the outcome you actually want, which is to copy the specific effect of the applied camo.

To actually fix this, the shader mod being used (in this case Oculus/Iris) would most likely need to provide some way for me to tell it what the block being rendered actually is
