### ISSUE TITLE
[Feature]: Double Slope Panel

### ISSUE THREAD

**Issue by TheDonutMasterg** [XFactHD/FramedBlocks#507] opened 2024-09-29 19:49 UTC
### Describe the feature

Hi XFact, thank you for the possibility of using the tism part of our brain. I would love if you could implement a double slope panel as unique block or the possibility of place two slabs together as demonstrated in the pictures. Love your work, cheers!
![Valhelsia 6 2024-09-29 2_46_11 PM](https://github.com/user-attachments/assets/fcffab9d-88f9-4a00-bbe1-d90e0f9647fa)
![Valhelsia 6 2024-09-29 2_45_06 PM](https://github.com/user-attachments/assets/73b0dc22-b864-45c4-80cc-d23d306b2324)

**Comment by XFactHD** [comment] 2024-09-29 22:30
Duplicate of #390.
These blocks are already planned and will be added when I get to them in "the list".

**Closed as completed by XFactHD** 2024-09-29 22:30 UTC
Labels: enhancement, new shape
