### ISSUE TITLE
[Mod Support]: Create encased shafts/cogs

### ISSUE THREAD

**Issue by mcm** [XFactHD/FramedBlocks#379] opened 2024-02-07 05:01 UTC
### The mod to integrate with

Create

### Describe the feature

Have you considered creating framed versions of Create's casings? Specifically it would be cool to be able to encase shafts and cogs in "framed casings"

**Comment by XFactHD** [comment] 2024-02-07 16:32
Duplicate of #348.
As mentioned in the linked issue, this is not possible at the moment.

**Closed as not planned** 2024-02-07 16:32 UTC
Labels: enhancement, mod support

**Comment by mcm** [comment] 2024-02-07 18:32
Is it more possible/doable through an integration with something like [Create Encased](https://github.com/iglee42/CreateCasing)?

**Comment by XFactHD** [comment] 2024-02-07 20:35
Unfortunately not. The issue is that I would need to inherit from Create's BlockEntities to avoid having to duplicate their code but at the same time I need to inherit from my own BlockEntity to have the FramedBlocks functionality, which is of course not possible. I had a similar issue with signs and the chiseled bookshelf, but their code was significantly simpler, so duplicating their code was viable.
