### ISSUE TITLE
[Feature]: Request for double/sliced(not sure what to actually call it) verticle/regular slope stairs

### ISSUE THREAD

**Issue by Flakxo** [XFactHD/FramedBlocks#506] opened 2024-09-28 14:19 UTC
### Describe the feature

![image](https://github.com/user-attachments/assets/2b727d2e-561d-4ad8-8d19-b3f40e690c99)

![image](https://github.com/user-attachments/assets/b8bcdd61-d32c-4838-8fc4-43a21f28b36c)
 It'd be really cool if there was a variant of the sloped stairs that allow for 2 different camos to be used, one for the panel part and one for the slope part, it could allow for cool things(at least im my case) for seamless merging of slopes and panels that could be implemented in builds in ways like the first image

not sure if relevant, but minecraft 1.21.1 neoforge 21.1.61 all the mods 10 0.59

**Comment by XFactHD** [comment] 2024-09-28 18:11
Duplicate of #368.
Both sliced (what you are suggesting) and double (the "missing" half-slope filled in) variants are already planned.

**Closed as completed by XFactHD** 2024-09-28 18:11 UTC
Labels: enhancement, new shape
