### ISSUE TITLE
[Feature]: Framed Divided Stairs Horizontal

### ISSUE THREAD

**Issue by f0kx** [XFactHD/FramedBlocks#341] opened 2023-11-16 14:18 UTC
### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/14795020/00ed1f28-07fc-44ba-ab77-5ef86c0f1d71)
For something like this having a Stair Divided Horizontal would be great so the First Step of the Stair in one Block and the little Step is another one. so the Cap could be closed there

**Comment by XFactHD** [comment] 2023-11-16 15:45
Duplicate of #165.
This type of block is already planned.

**Closed as completed by XFactHD** 2023-11-16 15:45 UTC
Labels: enhancement, new shape
