### ISSUE TITLE
Is there a way to make double slopes burn proof?

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#31] opened 2021-07-03 16:44 UTC
First: such a good mod! Love it.

I started a new survival world and tried out these double slopes for this (screenshot). I noticed they started burning, which makes sense since the frames are out of wood. But I placed blocks in it which aren't burnable so I hoped it makes it unburnable.

![Jre-legacy Screenshot 2021 07 03 - 18 40 40 70](https://user-images.githubusercontent.com/81813584/124361278-8f8e3500-dc2e-11eb-805b-3ed0c5e88a34.png)

Is this intended or will there be a work-around? 

Greetings (:

*Using FramedBlocks 2.8.0 on Enigmatica E6 - 0.5.3*

**Comment by XFactHD** [comment] 2021-07-03 18:51
I took a look at this and there is very little I can do about this right now.
The problem is that while the fire block asks the block itself wether it can burn (this is a patch in Forge), the lava block instead asks the blocks material if it can burn. I will check if this is something that Forge should change and get back to you.

You can be assured though that for now this will only look odd and not actually destroy the block.

**Comment by Erysch** [comment] 2021-07-04 11:05
> I took a look at this and there is very little I can do about this right now.
> The problem is that while the fire block asks the block itself wether it can burn (this is a patch in Forge), the lava block instead asks the blocks material if it can burn. I will check if this is something that Forge should change and get back to you.
> 
> You can be assured though that for now this will only look odd and not actually destroy the block.

Yeah, you're right. I just noticed that it only burns but doesn't destroy the block.
Thanks for your answer!

**Comment by XFactHD** [comment] 2021-07-04 12:01
I am going to keep this open for now because I still want to fix this.

In the future I might make the Framed Blocks actually flammable if no blocks are placed in them or atleast one of the block placed in them is flammable.

**Comment by HipHopHuman** [comment] 2021-07-07 18:19
If you're going to investigate making framed blocks respect the flammability of the material they're disguised with, is there any chance you could do the same thing with blast resistance?

**Comment by XFactHD** [comment] 2021-07-07 19:22
I will take a look, should be possible.

**Comment by XFactHD** [comment] 2021-07-22 17:35
I have now implemented dynamic flammability and blast resistance (yay for blast resistant obsidian slopes :D). This will however not have any impact on the initial issue of lava igniting framed blocks, I have yet to propose the necessary change to Forge. The flammability changes can be disabled in the common config.

A new version with these changes will go live on CF shortly.

**Comment by Erysch** [comment] 2021-07-23 14:01
That's cool, thumbs up!

**Comment by XFactHD** [comment] 2021-11-20 16:11
The fix for this is now included in Forge for both 1.16 (1.16.5-36.2.13 and above) and 1.17 (1.17.1-37.0.103 and above).

**Closed as completed by XFactHD** 2021-11-20 16:11 UTC
Labels: bug, enhancement, 1.16, 1.17, new mechanic
